CREATE TABLE role (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    role TEXT
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    age INT,
    password TEXT NOT NULL
);
